### ISSUE TITLE
empty data attributes

### ISSUE THREAD

**Issue by missinglink** [geocodeearth/autocomplete-element#20]
empty data attributes generate empty querystring params, eg:

`<ge-autocomplete sources="" />` will add `?sources=` to the querystring.

use of this library from templating is easier if the data attributes are always rendered in the HTML but only populated when required.

this ticket is to investigate solutions to detecting empty data attributes and avoiding generating querystring params.

**Comment by mxlje** [comment]
This has been fixed in `core-js v0.0.8` and is included in the latest release as `v0.5.0`.
